name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        # 安装任何必要的依赖项，例如 Xcode 命令行工具
        xcode-select --install
        # 如果需要其他依赖项，可以在这里添加

    - name: Run Makefile
      run: |
        make clean
        make all

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Odyssey IPA
        path: Odyssey.ipa
