name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        ref: ${{ github.ref }}

    - name: Install dependencies
      run: |
        brew install make
        brew install ldid

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1.0'

    - name: Run Makefile
      run: |
        make clean
        make all

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Odyssey IPA
        path: Odyssey.ipa
